2024-01-25 10:01:44 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 10:01:44 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 10:01:55 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 10:01:59 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 10:01:59 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 10:02:36 India Standard TimeINFO:root:Client connected
2024-01-25 10:02:36 India Standard TimeINFO:root:userid_data: 65b0fab206899c40a9635527
2024-01-25 10:02:36 India Standard TimeINFO:root:response: <Response [200]>
2024-01-25 10:02:37 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-25 10:02:37 India Standard TimeINFO:root:userid_data: 65b0fab206899c40a9635527
2024-01-25 10:02:37 India Standard TimeINFO:root:response: <Response [200]>
2024-01-25 10:02:37 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-25 10:02:48 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-25 10:02:48 India Standard TimeINFO:root:Client disconnected
2024-01-25 10:03:26 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 10:03:27 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 10:03:31 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 10:03:31 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 10:17:04 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\fnl_d.py', reloading
2024-01-25 10:17:05 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 10:17:12 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 10:17:12 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 10:19:21 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 10:19:22 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 10:19:26 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 10:19:26 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 10:32:01 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 10:32:02 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 10:32:07 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 10:32:07 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 10:48:37 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 10:48:42 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 10:48:42 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 15:46:55 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 15:47:00 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 15:47:00 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 15:47:15 India Standard TimeINFO:root:Client connected
2024-01-25 15:47:18 India Standard TimeINFO:root:Client disconnected
2024-01-25 15:47:18 India Standard TimeINFO:root:Client connected
2024-01-25 15:47:19 India Standard TimeINFO:root:Client disconnected
2024-01-25 15:47:19 India Standard TimeINFO:root:Client connected
2024-01-25 15:47:19 India Standard TimeINFO:root:Client disconnected
2024-01-25 15:47:19 India Standard TimeINFO:root:Client connected
2024-01-25 15:47:20 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:22 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:22 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:24 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:25 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:26 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:27 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:27 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:28 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:29 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:30 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:31 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:32 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 15:47:32 India Standard TimeINFO:root:Client disconnected
2024-01-25 16:04:46 India Standard TimeINFO:root:Client connected
2024-01-25 16:04:46 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 16:04:47 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 16:04:48 India Standard TimeINFO:root:Client disconnected
2024-01-25 16:05:39 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 16:05:40 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 16:05:46 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 16:05:51 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 16:05:51 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 16:05:53 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask_socketio\__init__.py", line 823, in _handle_event
    ret = handler(auth)
  File "D:\Projects\Face_Detection\face_matched_livespoof\spoofing_face_match_application.py", line 59, in handle_connect
    id = data.id
AttributeError: 'NoneType' object has no attribute 'id'
2024-01-25 16:06:32 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 16:06:32 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 16:06:40 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 16:06:44 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 16:06:44 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 16:06:56 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask_socketio\__init__.py", line 823, in _handle_event
    ret = handler(auth)
  File "D:\Projects\Face_Detection\face_matched_livespoof\spoofing_face_match_application.py", line 59, in handle_connect
    user_id= data.get('id')
AttributeError: 'NoneType' object has no attribute 'get'
2024-01-25 16:07:05 India Standard TimeINFO:root:Client disconnected
2024-01-25 16:07:14 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 16:07:19 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 16:07:19 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 16:37:55 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\app.py', reloading
2024-01-25 16:37:56 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 16:38:01 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 16:38:01 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 16:50:26 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 16:50:27 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 16:50:31 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 16:50:31 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 17:15:11 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 17:15:12 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 17:15:16 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 17:15:16 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 17:17:42 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 17:17:42 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 17:17:46 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 17:17:46 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 17:33:56 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 17:33:56 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 17:34:00 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 17:34:00 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 17:38:56 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 17:38:56 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 18:53:43 India Standard TimeINFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-01-25 18:53:43 India Standard TimeINFO:werkzeug:[33mPress CTRL+C to quit[0m
2024-01-25 18:53:43 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 18:53:47 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 18:53:47 India Standard TimeINFO:werkzeug: * Debugger PIN: 108-494-101
2024-01-25 18:54:25 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 18:54:25 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 18:54:32 India Standard TimeINFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5001
2024-01-25 18:54:32 India Standard TimeINFO:werkzeug:[33mPress CTRL+C to quit[0m
2024-01-25 18:54:32 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 18:54:36 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 18:54:36 India Standard TimeINFO:werkzeug: * Debugger PIN: 108-494-101
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "GET / HTTP/1.1" 200 -
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "GET /socket.io/?EIO=4&transport=polling&t=Or0opyV HTTP/1.1" 200 -
2024-01-25 18:54:38 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 535, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 3 were given
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "POST /socket.io/?EIO=4&transport=polling&t=Or0opyf&sid=rK1HM-FnZoLWBJUuAAAA HTTP/1.1" 200 -
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "[35m[1mGET /socket.io/?EIO=4&transport=websocket&sid=rK1HM-FnZoLWBJUuAAAA HTTP/1.1[0m" 500 -
2024-01-25 18:54:38 India Standard TimeERROR:engineio.server:disconnect handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 660, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 562, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_disconnect() takes 0 positional arguments but 1 was given
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "POST /socket.io/?EIO=4&transport=polling&t=Or0oq2M&sid=rK1HM-FnZoLWBJUuAAAA HTTP/1.1" 200 -
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "GET / HTTP/1.1" 200 -
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "GET /socket.io/?EIO=4&transport=polling&t=Or0oq2y HTTP/1.1" 200 -
2024-01-25 18:54:38 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 535, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 3 were given
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "POST /socket.io/?EIO=4&transport=polling&t=Or0oq3g&sid=6usa6JFE5QyXdWRVAAAC HTTP/1.1" 200 -
2024-01-25 18:54:38 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:54:38] "[35m[1mGET /socket.io/?EIO=4&transport=websocket&sid=6usa6JFE5QyXdWRVAAAC HTTP/1.1[0m" 500 -
2024-01-25 18:55:23 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:55:23] "[31m[1mGET /socket.io/?EIO=4&transport=polling&t=Or0opyh&sid=rK1HM-FnZoLWBJUuAAAA HTTP/1.1[0m" 400 -
2024-01-25 18:55:23 India Standard TimeERROR:engineio.server:disconnect handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 16, in poll
    packets = [self.queue.get(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\eventlet\queue.py", line 322, in get
    return waiter.wait()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\eventlet\queue.py", line 141, in wait
    return get_hub().switch()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\eventlet\hubs\hub.py", line 313, in switch
    return self.greenlet.switch()
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 97, in handle_get_request
    packets = self.poll()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 20, in poll
    raise exceptions.QueueEmpty()
engineio.exceptions.QueueEmpty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 660, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 562, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_disconnect() takes 0 positional arguments but 1 was given
2024-01-25 18:55:23 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:55:23] "[31m[1mGET /socket.io/?EIO=4&transport=polling&t=Or0oq3h&sid=6usa6JFE5QyXdWRVAAAC HTTP/1.1[0m" 400 -
2024-01-25 18:55:23 India Standard TimeERROR:engineio.server:Invalid session 6usa6JFE5QyXdWRVAAAC (further occurrences of this error will be logged with level INFO)
2024-01-25 18:55:23 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:55:23] "[31m[1mPOST /socket.io/?EIO=4&transport=polling&t=Or0o_3f&sid=6usa6JFE5QyXdWRVAAAC HTTP/1.1[0m" 400 -
2024-01-25 18:55:25 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:55:25] "GET /socket.io/?EIO=4&transport=polling&t=Or0o_ML HTTP/1.1" 200 -
2024-01-25 18:55:25 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 535, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 3 were given
2024-01-25 18:55:25 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:55:25] "POST /socket.io/?EIO=4&transport=polling&t=Or0o_MY&sid=TujIkIFPJc8XIqH7AAAE HTTP/1.1" 200 -
2024-01-25 18:55:25 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:55:25] "[35m[1mGET /socket.io/?EIO=4&transport=websocket&sid=TujIkIFPJc8XIqH7AAAE HTTP/1.1[0m" 500 -
2024-01-25 18:56:10 India Standard TimeERROR:engineio.server:disconnect handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 16, in poll
    packets = [self.queue.get(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\eventlet\queue.py", line 322, in get
    return waiter.wait()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\eventlet\queue.py", line 141, in wait
    return get_hub().switch()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\eventlet\hubs\hub.py", line 313, in switch
    return self.greenlet.switch()
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 97, in handle_get_request
    packets = self.poll()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 20, in poll
    raise exceptions.QueueEmpty()
engineio.exceptions.QueueEmpty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 660, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 562, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_disconnect() takes 0 positional arguments but 1 was given
2024-01-25 18:56:10 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:56:10] "[31m[1mGET /socket.io/?EIO=4&transport=polling&t=Or0o_Ma&sid=TujIkIFPJc8XIqH7AAAE HTTP/1.1[0m" 400 -
2024-01-25 18:56:10 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:56:10] "[31m[1mPOST /socket.io/?EIO=4&transport=polling&t=Or0pALy&sid=TujIkIFPJc8XIqH7AAAE HTTP/1.1[0m" 400 -
2024-01-25 18:56:12 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:56:12] "GET /socket.io/?EIO=4&transport=polling&t=Or0pAsM HTTP/1.1" 200 -
2024-01-25 18:56:12 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 535, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 3 were given
2024-01-25 18:56:12 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:56:12] "POST /socket.io/?EIO=4&transport=polling&t=Or0pAss&sid=HfDFZ93UcEZbPJ9eAAAG HTTP/1.1" 200 -
2024-01-25 18:56:12 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:56:12] "[35m[1mGET /socket.io/?EIO=4&transport=websocket&sid=HfDFZ93UcEZbPJ9eAAAG HTTP/1.1[0m" 500 -
2024-01-25 18:56:54 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-25 18:56:54 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 18:57:01 India Standard TimeINFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5001
2024-01-25 18:57:01 India Standard TimeINFO:werkzeug:[33mPress CTRL+C to quit[0m
2024-01-25 18:57:01 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 18:57:05 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 18:57:05 India Standard TimeINFO:werkzeug: * Debugger PIN: 108-494-101
2024-01-25 18:57:06 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:57:06] "GET /socket.io/?EIO=4&transport=polling&t=Or0pO27 HTTP/1.1" 200 -
2024-01-25 18:57:06 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 535, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 3 were given
2024-01-25 18:57:06 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:57:06] "POST /socket.io/?EIO=4&transport=polling&t=Or0pO34&sid=3Bw9VsdwvYVmTwxeAAAA HTTP/1.1" 200 -
2024-01-25 18:57:06 India Standard TimeINFO:werkzeug:127.0.0.1 - - [25/Jan/2024 18:57:06] "[35m[1mGET /socket.io/?EIO=4&transport=websocket&sid=3Bw9VsdwvYVmTwxeAAAA HTTP/1.1[0m" 500 -
2024-01-25 18:59:18 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 535, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 0 positional arguments but 3 were given
2024-01-25 18:59:38 India Standard TimeERROR:engineio.server:disconnect handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 660, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 562, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_disconnect() takes 0 positional arguments but 1 was given
2024-01-25 19:01:01 India Standard TimeERROR:engineio.server:message handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 532, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 642, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 535, in _handle_connect
    success = self._trigger_event(
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_connect() takes 1 positional argument but 3 were given
2024-01-25 19:01:21 India Standard TimeERROR:engineio.server:disconnect handler error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 431, in run_handler
    return self.handlers[event](*args)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 660, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 562, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 609, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: handle_disconnect() takes 0 positional arguments but 1 was given
2024-01-25 19:09:09 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-25 19:09:13 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-25 19:09:13 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-25 19:09:22 India Standard TimeINFO:root:Client connected
2024-01-25 19:09:22 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:23 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:24 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:25 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:27 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:28 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:29 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:29 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:31 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:32 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:33 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:34 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:34 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:36 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:37 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:38 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:38 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:39 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:41 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:42 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:43 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:44 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:44 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:46 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:47 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:48 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:49 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:49 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:51 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:52 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:53 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:53 India Standard TimeINFO:root:Client connected
2024-01-25 19:09:53 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:54 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:54 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:55 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:55 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:55 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:57 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:57 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:58 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:58 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:59 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:09:59 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:00 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:00 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:01 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:01 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:02 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:02 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:03 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:03 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:05 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:05 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:06 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:06 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:06 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:07 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:07 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:07 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:08 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:09 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:09 India Standard TimeINFO:root:Client disconnected
2024-01-25 19:10:09 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:10 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:11 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-25 19:10:12 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:14:16 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 10:14:20 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 10:14:20 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 10:18:18 India Standard TimeINFO:root:Client connected
2024-01-29 10:18:18 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:18:18 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:18:18 India Standard TimeERROR:root:Error: 'str' object has no attribute 'spl'
2024-01-29 10:18:18 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:18:19 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:18:19 India Standard TimeERROR:root:Error: 'str' object has no attribute 'spl'
2024-01-29 10:18:29 India Standard TimeINFO:root:====result {'matched': False, 'message': 'Please provide a real face!!'}
2024-01-29 10:18:29 India Standard TimeERROR:root:Error: Server.emit() got an unexpected keyword argument 'sid'
2024-01-29 10:18:39 India Standard TimeERROR:root:Error: Server.emit() got an unexpected keyword argument 'sid'
2024-01-29 10:18:49 India Standard TimeERROR:root:Error: Server.emit() got an unexpected keyword argument 'sid'
2024-01-29 10:18:59 India Standard TimeERROR:root:Error: Server.emit() got an unexpected keyword argument 'sid'
2024-01-29 10:22:01 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 10:22:01 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 10:22:07 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 10:22:12 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 10:22:12 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 10:26:30 India Standard TimeINFO:root:Client connected
2024-01-29 10:26:30 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:26:31 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:26:31 India Standard TimeERROR:root:Error: 'str' object has no attribute 'spl'
2024-01-29 10:26:31 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:26:31 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:26:31 India Standard TimeERROR:root:Error: 'str' object has no attribute 'spl'
2024-01-29 10:26:41 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 10:26:41 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:26:48 India Standard TimeINFO:root:Client connected
2024-01-29 10:26:49 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:26:49 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:26:49 India Standard TimeERROR:root:Error: 'str' object has no attribute 'spl'
2024-01-29 10:26:49 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:26:49 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:26:49 India Standard TimeERROR:root:Error: 'str' object has no attribute 'spl'
2024-01-29 10:26:53 India Standard TimeINFO:root:====result {'matched': False, 'message': 'No face detected!!'}:
2024-01-29 10:26:53 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:27:09 India Standard TimeINFO:root:Client connected
2024-01-29 10:27:09 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:27:09 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:27:09 India Standard TimeERROR:root:Error: 'str' object has no attribute 'spl'
2024-01-29 10:27:09 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:27:10 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:27:10 India Standard TimeERROR:root:Error: 'str' object has no attribute 'spl'
2024-01-29 10:27:20 India Standard TimeINFO:root:====result {'matched': False, 'message': 'Please provide a real face!!'}
2024-01-29 10:27:20 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:27:46 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 10:27:47 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 10:27:51 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 10:27:51 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 10:28:01 India Standard TimeINFO:root:Client connected
2024-01-29 10:28:01 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:01 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:02 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:02 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:02 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:03 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:12 India Standard TimeINFO:root:====result {'matched': False, 'message': 'Please provide a real face!!'}
2024-01-29 10:28:12 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:28:17 India Standard TimeINFO:root:Client connected
2024-01-29 10:28:17 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:17 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:18 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:18 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:18 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:19 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:22 India Standard TimeINFO:root:====result {'matched': False, 'message': 'Please provide a real face!!'}
2024-01-29 10:28:22 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:28:26 India Standard TimeINFO:root:Client connected
2024-01-29 10:28:26 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:26 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:26 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:26 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:27 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:27 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:32 India Standard TimeINFO:root:====result {'matched': False, 'message': 'Please provide a real face!!'}
2024-01-29 10:28:32 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:28:33 India Standard TimeINFO:root:Client connected
2024-01-29 10:28:33 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:33 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:34 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:34 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:34 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:35 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:42 India Standard TimeINFO:root:====result {'matched': False, 'message': 'Please provide a real face!!'}
2024-01-29 10:28:42 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:28:43 India Standard TimeINFO:root:Client connected
2024-01-29 10:28:43 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:44 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:44 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:44 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:44 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:45 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:52 India Standard TimeINFO:root:====result {'matched': False, 'message': 'Please provide a real face!!'}
2024-01-29 10:28:52 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:28:57 India Standard TimeINFO:root:Client connected
2024-01-29 10:28:57 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:57 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:58 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:28:58 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:28:58 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:28:59 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:29:03 India Standard TimeINFO:root:====result {'matched': True, 'name': '658c10d2da185563578215d3', 'confidence': 0.46367223101711985, 'message': 'Match Found!'}
2024-01-29 10:29:03 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:29:30 India Standard TimeINFO:root:Client connected
2024-01-29 10:29:30 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:29:31 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:29:31 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:29:31 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 10:29:31 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 10:29:32 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 10:29:42 India Standard TimeINFO:root:====result {'matched': True, 'name': '658c10d2da185563578215d3', 'confidence': 0.41403659989763064, 'message': 'Match Found!'}
2024-01-29 10:29:42 India Standard TimeINFO:root:Client disconnected
2024-01-29 10:40:49 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 10:40:53 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 10:40:53 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 10:42:34 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 10:42:38 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 10:42:38 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 10:49:05 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 10:49:09 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 10:49:09 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 10:55:56 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 10:56:00 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 10:56:00 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 10:56:07 India Standard TimeINFO:root:Client connected
2024-01-29 10:56:08 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 10:56:09 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 10:56:11 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 10:56:12 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 10:56:12 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 10:56:13 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 10:56:14 India Standard TimeINFO:root:Client disconnected
2024-01-29 11:05:25 India Standard TimeINFO:root:Client connected
2024-01-29 11:05:25 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 11:05:25 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 11:05:26 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 11:05:26 India Standard TimeINFO:root:imagedatabase length 1 :
2024-01-29 11:05:26 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 11:05:26 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 11:05:27 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 11:05:27 India Standard TimeINFO:root:imagedatabase length 1 :
2024-01-29 11:05:37 India Standard TimeINFO:root:=====imagedatabase 0:
2024-01-29 11:05:37 India Standard TimeINFO:root:====result {'matched': True, 'name': '658c10d2da185563578215d3', 'confidence': 0.42588394005667385, 'message': 'Match Found!'}:
2024-01-29 11:05:37 India Standard TimeINFO:root:Client disconnected
2024-01-29 11:05:54 India Standard TimeINFO:root:Client connected
2024-01-29 11:05:54 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 11:05:54 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 11:05:55 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 11:05:55 India Standard TimeINFO:root:imagedatabase length 1 :
2024-01-29 11:05:55 India Standard TimeINFO:root:userid_data: 658c10d2da185563578215d3
2024-01-29 11:05:55 India Standard TimeINFO:root:response: <Response [200]>
2024-01-29 11:05:56 India Standard TimeINFO:root:faceencoding of api face: 128
2024-01-29 11:05:56 India Standard TimeINFO:root:imagedatabase length 1 :
2024-01-29 11:06:05 India Standard TimeINFO:root:=====imagedatabase 0:
2024-01-29 11:06:05 India Standard TimeINFO:root:====result {'matched': True, 'name': '658c10d2da185563578215d3', 'confidence': 0.5961985614825196, 'message': 'Match Found!'}:
2024-01-29 11:06:05 India Standard TimeINFO:root:Client disconnected
2024-01-29 11:06:49 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\fnl_d.py', reloading
2024-01-29 11:06:50 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 11:06:54 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 11:06:54 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 11:07:56 India Standard TimeINFO:waitress:Serving on http://0.0.0.0:5002
2024-01-29 11:08:41 India Standard TimeERROR:waitress:Exception while serving /socket.io/
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask_socketio\__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 258, in handle_request
    r = self._handle_connect(environ, start_response,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 398, in _handle_connect
    ret = s.handle_get_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 90, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 146, in _upgrade_websocket
    ws(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\async_drivers\eventlet.py", line 40, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2024-01-29 11:09:00 India Standard TimeERROR:waitress:Exception while serving /socket.io/
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask_socketio\__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 258, in handle_request
    r = self._handle_connect(environ, start_response,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 398, in _handle_connect
    ret = s.handle_get_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 90, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 146, in _upgrade_websocket
    ws(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\async_drivers\eventlet.py", line 40, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2024-01-29 11:09:06 India Standard TimeERROR:waitress:Exception while serving /socket.io/
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask_socketio\__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 258, in handle_request
    r = self._handle_connect(environ, start_response,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 398, in _handle_connect
    ret = s.handle_get_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 90, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 146, in _upgrade_websocket
    ws(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\async_drivers\eventlet.py", line 40, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2024-01-29 11:09:14 India Standard TimeERROR:waitress:Exception while serving /socket.io/
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\flask_socketio\__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\socketio\server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 258, in handle_request
    r = self._handle_connect(environ, start_response,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\server.py", line 398, in _handle_connect
    ret = s.handle_get_request(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 90, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\socket.py", line 146, in _upgrade_websocket
    ws(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\FaceDetection_Antispoofing_System_ML\venv\lib\site-packages\engineio\async_drivers\eventlet.py", line 40, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
2024-01-29 11:24:01 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 11:24:05 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 11:24:05 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 11:24:44 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 11:24:48 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 11:24:48 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 11:26:59 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\extra_code.py', reloading
2024-01-29 11:26:59 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 11:27:04 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 11:27:04 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 11:27:05 India Standard TimeINFO:root:Client connected
2024-01-29 11:27:41 India Standard TimeINFO:root:Client connected
2024-01-29 11:27:43 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:44 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:45 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:47 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:48 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:49 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:49 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:50 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:52 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:53 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:54 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:55 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:56 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:56 India Standard TimeINFO:root:Client connected
2024-01-29 11:27:56 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:57 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:57 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:59 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:59 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:27:59 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:00 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:00 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:01 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:04 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:05 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:05 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:06 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:06 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:07 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:07 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:07 India Standard TimeINFO:root:Client connected
2024-01-29 11:28:07 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:08 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:08 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:09 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:09 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:09 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:10 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:10 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:10 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:11 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:11 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:11 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:12 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:12 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:12 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:13 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:13 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:13 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:14 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:14 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:14 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:14 India Standard TimeINFO:root:Client disconnected
2024-01-29 11:28:14 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:15 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:15 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:16 India Standard TimeINFO:root:Client disconnected
2024-01-29 11:28:16 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:16 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 11:28:16 India Standard TimeINFO:root:Client disconnected
2024-01-29 13:27:57 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 13:28:01 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 13:28:01 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 13:28:31 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 13:28:31 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 13:28:36 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 13:28:36 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:35:33 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:35:34 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:35:38 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:35:38 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:36:09 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:36:10 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:36:14 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:36:14 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:36:22 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:36:27 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:36:27 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:36:39 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:36:39 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:36:47 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:36:51 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:36:51 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:37:33 India Standard TimeINFO:root:Client connected
2024-01-29 14:37:35 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:37 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:38 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:39 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:40 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:40 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:42 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:43 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:44 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:45 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:46 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:47 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:48 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:49 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:50 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:51 India Standard TimeERROR:root:Error: string indices must be integers
2024-01-29 14:37:51 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:37:52 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:38:05 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:38:09 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:38:09 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:38:10 India Standard TimeINFO:root:Client connected
2024-01-29 14:38:13 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:14 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:15 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:15 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:16 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:17 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:17 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:18 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:19 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:20 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:20 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:21 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:22 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:22 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:23 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:24 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:24 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:25 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:26 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:26 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:27 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:29 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:30 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:31 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:31 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:32 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:33 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:33 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:34 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:35 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:35 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:36 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:37 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:38:37 India Standard TimeINFO:root:Client disconnected
2024-01-29 14:38:53 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:38:57 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:38:57 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:39:03 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:39:03 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:39:07 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:39:07 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:39:08 India Standard TimeINFO:root:Client connected
2024-01-29 14:39:09 India Standard TimeERROR:root:Error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:801: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'

2024-01-29 14:39:11 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:12 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:13 India Standard TimeINFO:root:====result {'matched': False, 'message': 'No face detected!!'}:
2024-01-29 14:39:14 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:15 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:16 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:17 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:18 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:19 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:20 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:21 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:22 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:23 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:24 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:24 India Standard TimeINFO:root:====result {'matched': False, 'message': 'No face detected!!'}:
2024-01-29 14:39:26 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:26 India Standard TimeINFO:root:====result {'matched': False, 'message': 'No face detected!!'}:
2024-01-29 14:39:28 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:29 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:30 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:39:30 India Standard TimeINFO:root:Client disconnected
2024-01-29 14:42:01 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:42:01 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:42:06 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:42:06 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:43:32 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:43:32 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:43:37 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:43:37 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:43:54 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:43:54 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:43:58 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:43:58 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:44:12 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:44:18 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:44:22 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:44:22 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:45:04 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:45:05 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:45:14 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:45:18 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:45:18 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:45:49 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:45:49 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:45:55 India Standard TimeINFO:werkzeug: * Restarting with stat
2024-01-29 14:45:59 India Standard TimeWARNING:werkzeug: * Debugger is active!
2024-01-29 14:45:59 India Standard TimeINFO:werkzeug: * Debugger PIN: 801-066-297
2024-01-29 14:46:02 India Standard TimeINFO:root:Client connected
2024-01-29 14:46:03 India Standard TimeERROR:root:Error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:801: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'

2024-01-29 14:46:05 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:06 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:07 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:08 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:09 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:10 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:11 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:12 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:12 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:13 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:14 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:15 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:15 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:16 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:17 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:18 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:19 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:20 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:21 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:21 India Standard TimeINFO:root:====result {'matched': False, 'name': 'Unknown', 'message': 'not matching face with the DB stored image'}
2024-01-29 14:46:21 India Standard TimeINFO:root:Client disconnected
2024-01-29 14:47:20 India Standard TimeINFO:werkzeug: * Detected change in 'D:\\Projects\\Face_Detection\\face_matched_livespoof\\spoofing_face_match_application.py', reloading
2024-01-29 14:47:21 India Standard TimeINFO:werkzeug: * Restarting with stat
